name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bats
        run: brew install bats-core
      - name: Run tests
        run: make test

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: diskmute.sh
          generate_release_notes: true

  update-formula:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get release info
        id: release
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          URL="https://github.com/tobyvee/diskmute/archive/${TAG}.tar.gz"
          SHA256=$(curl -sL $URL | sha256sum | cut -d' ' -f1)
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "sha256=$SHA256" >> $GITHUB_OUTPUT
      - name: Update formula
        run: |
          sed -i "s|url \".*\"|url \"${{ steps.release.outputs.url }}\"|" diskmute.rb
          sed -i "s|sha256 \".*\"|sha256 \"${{ steps.release.outputs.sha256 }}\"|" diskmute.rb
      - name: Commit formula
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add diskmute.rb
          git commit -m "Update formula for ${{ steps.release.outputs.tag }}"
          git push